name: on-schedule
run-name: on schedule

on:
  schedule:
    # weekly
    - cron: "0 0 * * 1"

  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  update-citations:
    # only run on user instance of template, not template itself
    if: github.repository != 'greenelab/lab-website-template'
    uses: ./.github/workflows/update-citations.yaml
    with:
      open-pr: true
  keepalive-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liskin/gh-workflow-keepalive@v1
